//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MechanicsForum.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProblemsMedia
    {
        public int Id { get; set; }
        public int ProblemID { get; set; }
        public string MediaPath { get; set; }
    
        public virtual Problem Problem { get; set; }
    }
}
